FROM python:3.13-slim

WORKDIR /app

COPY requirements-test.txt .
RUN pip install -r requirements-test.txt

COPY pytest.ini .
COPY src src
COPY tests tests

CMD ["pytest", "-q", "--html=/reports/testreport.html"]
